// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeverfadePos.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeverfadePos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903033503_AddSharedDeviceAttendance")]
    partial class AddSharedDeviceAttendance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeverfadePos.Api.Entities.Absensi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("CheckIn")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("CheckInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("CheckOutAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KaryawanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OutsideSchedule")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KaryawanId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "KaryawanId", "Tanggal")
                        .IsUnique();

                    b.ToTable("absensis", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.AttendanceCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbsensiId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterData")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BeforeData")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("CorrectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedByUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AbsensiId");

                    b.HasIndex("CorrectedByUserId");

                    b.HasIndex("TenantId", "AbsensiId", "CreatedAt");

                    b.ToTable("attendance_corrections", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.AttendancePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbsenceThresholdMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GraceMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("attendance_policies", null, t =>
                        {
                            t.HasCheckConstraint("CK_attendance_policies_AbsenceThresholdMinutes", "\"AbsenceThresholdMinutes\" BETWEEN 1 AND 720");

                            t.HasCheckConstraint("CK_attendance_policies_GraceMinutes", "\"GraceMinutes\" BETWEEN 0 AND 180");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Hp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Poin")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTransaksi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.EmployeeScheduleException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("KaryawanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("KaryawanId");

                    b.HasIndex("TenantId", "KaryawanId", "Date")
                        .IsUnique();

                    b.ToTable("employee_schedule_exceptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_employee_schedule_exceptions_Type", "\"Type\" IN ('leave', 'holiday', 'changed_shift', 'off')");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.EmployeeWeeklySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KaryawanId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KaryawanId");

                    b.HasIndex("TenantId", "KaryawanId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("employee_weekly_schedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_employee_weekly_schedules_DayOfWeek", "\"DayOfWeek\" BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Karyawan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Gaji")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PinFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PinUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("TanggalMasuk")
                        .HasColumnType("date");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PinFingerprint")
                        .IsUnique()
                        .HasFilter("\"PinFingerprint\" IS NOT NULL");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("karyawans", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderPaymentRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("QrString")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique();

                    b.HasIndex("ProviderPaymentRequestId")
                        .IsUnique();

                    b.HasIndex("ProviderReferenceId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_Status", "\"Status\" IN ('creating', 'pending', 'paid', 'failed')");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PaymentLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WithdrawalRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WithdrawalRequestId")
                        .IsUnique();

                    b.HasIndex("PaymentId", "EntryType")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("payment_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_ledger_entries_EntryType", "\"EntryType\" IN ('payment_credit', 'withdrawal_debit')");

                            t.HasCheckConstraint("CK_payment_ledger_entries_Source", "(\"EntryType\" = 'payment_credit' AND \"PaymentId\" IS NOT NULL AND \"TransactionId\" IS NOT NULL AND \"WithdrawalRequestId\" IS NULL AND \"ProviderReference\" IS NOT NULL) OR (\"EntryType\" = 'withdrawal_debit' AND \"PaymentId\" IS NULL AND \"TransactionId\" IS NULL AND \"WithdrawalRequestId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PaymentRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderPaymentRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("Provider", "ProviderPaymentRequestId")
                        .IsUnique();

                    b.ToTable("payment_routes", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PaymentWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProviderEventKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ProviderEventKey")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("payment_webhook_events", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PlatformAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorPlatformUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorPlatformUserId", "CreatedAt");

                    b.HasIndex("EventType", "CreatedAt");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("platform_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_platform_audit_events_EventType", "\"EventType\" IN ('TENANT_PROVISIONED', 'TENANT_ACTIVATED', 'TENANT_SUSPENDED', 'TENANT_BUSINESS_PROFILE_CHANGED')");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("platform_users", null, t =>
                        {
                            t.HasCheckConstraint("CK_platform_users_Role", "\"Role\" = 'superadmin'");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("HargaJual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HargaModal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Stok")
                        .HasColumnType("integer");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Kode")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FooterStruk")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HeaderStruk")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MinStok")
                        .HasColumnType("integer");

                    b.Property<string>("NamaToko")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PoinRate")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowPoint")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowTax")
                        .HasColumnType("boolean");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.SharedPosDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedUnlockCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique();

                    b.ToTable("shared_pos_devices", null, t =>
                        {
                            t.HasCheckConstraint("CK_shared_pos_devices_FailedUnlockCount", "\"FailedUnlockCount\" >= 0");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.SharedPosSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KaryawanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("KaryawanId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "DeviceId", "ExpiresAtUtc");

                    b.ToTable("shared_pos_sessions", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.StockHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdukId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProdukNama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StokAkhir")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProdukId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProdukId");

                    b.ToTable("stock_histories", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("general_retail");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NamaToko")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessType");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_tenants_BusinessType", "\"BusinessType\" IN ('general_retail', 'food_beverage', 'laundry', 'salon_barbershop')");

                            t.HasCheckConstraint("CK_tenants_Status", "\"Status\" IN ('active', 'suspended')");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.TenantAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorKaryawanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorKaryawanId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("tenant_audit_events", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Dibayar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Disc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DiscAmt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kasir")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("KasirId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Kembalian")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NoTrx")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("paid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxAmt")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "NoTrx")
                        .IsUnique();

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_transactions_Status", "\"Status\" IN ('pending_payment', 'paid', 'failed')");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.TransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HargaJual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_items", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedByPlatformUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByPlatformUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("withdrawal_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_withdrawal_requests_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_withdrawal_requests_Status", "\"Status\" IN ('requested', 'paid', 'rejected')");
                        });
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.WithdrawalRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WithdrawalRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WithdrawalRequestId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("withdrawal_routes", (string)null);
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Absensi", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Karyawan", "Karyawan")
                        .WithMany("Absensis")
                        .HasForeignKey("KaryawanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Absensis")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karyawan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.AttendanceCorrection", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Absensi", "Absensi")
                        .WithMany("Corrections")
                        .HasForeignKey("AbsensiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.User", "CorrectedByUser")
                        .WithMany()
                        .HasForeignKey("CorrectedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("AttendanceCorrections")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Absensi");

                    b.Navigation("CorrectedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.AttendancePolicy", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("AttendancePolicies")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Customer", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.EmployeeScheduleException", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Karyawan", "Karyawan")
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("KaryawanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("EmployeeScheduleExceptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karyawan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.EmployeeWeeklySchedule", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Karyawan", "Karyawan")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("KaryawanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("EmployeeWeeklySchedules")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karyawan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Karyawan", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Karyawans")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("NeverfadePos.Api.Entities.Karyawan", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Payment", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Transaction", "Transaction")
                        .WithOne("Payment")
                        .HasForeignKey("NeverfadePos.Api.Entities.Payment", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PaymentLedgerEntry", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Payment", "Payment")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("PaymentLedgerEntries")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeverfadePos.Api.Entities.WithdrawalRequest", "WithdrawalRequest")
                        .WithOne("LedgerEntry")
                        .HasForeignKey("NeverfadePos.Api.Entities.PaymentLedgerEntry", "WithdrawalRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");

                    b.Navigation("Tenant");

                    b.Navigation("Transaction");

                    b.Navigation("WithdrawalRequest");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PaymentRoute", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Payment", "Payment")
                        .WithOne()
                        .HasForeignKey("NeverfadePos.Api.Entities.PaymentRoute", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("PaymentRoutes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PaymentWebhookEvent", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Payment", "Payment")
                        .WithMany("WebhookEvents")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("PaymentWebhookEvents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PlatformAuditEvent", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.PlatformUser", "ActorPlatformUser")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ActorPlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("PlatformAuditEvents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorPlatformUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Product", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Settings", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Settings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.SharedPosDevice", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("SharedPosDevices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.SharedPosSession", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.SharedPosDevice", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Karyawan", "Karyawan")
                        .WithMany("SharedPosSessions")
                        .HasForeignKey("KaryawanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("SharedPosSessions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Karyawan");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.StockHistory", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Product", "Product")
                        .WithMany("StockHistories")
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("StockHistories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.TenantAuditEvent", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Karyawan", "ActorKaryawan")
                        .WithMany()
                        .HasForeignKey("ActorKaryawanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NeverfadePos.Api.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("TenantAuditEvents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorKaryawan");

                    b.Navigation("ActorUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Transaction", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Transactions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.TransactionItem", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Product", "Product")
                        .WithMany("TransactionItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tenant");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.User", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.WithdrawalRequest", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.PlatformUser", "ProcessedByPlatformUser")
                        .WithMany("ProcessedWithdrawalRequests")
                        .HasForeignKey("ProcessedByPlatformUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NeverfadePos.Api.Entities.User", "RequestedByUser")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessedByPlatformUser");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.WithdrawalRoute", b =>
                {
                    b.HasOne("NeverfadePos.Api.Entities.Tenant", "Tenant")
                        .WithMany("WithdrawalRoutes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NeverfadePos.Api.Entities.WithdrawalRequest", "WithdrawalRequest")
                        .WithOne()
                        .HasForeignKey("NeverfadePos.Api.Entities.WithdrawalRoute", "WithdrawalRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("WithdrawalRequest");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Absensi", b =>
                {
                    b.Navigation("Corrections");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Karyawan", b =>
                {
                    b.Navigation("Absensis");

                    b.Navigation("ScheduleExceptions");

                    b.Navigation("SharedPosSessions");

                    b.Navigation("WeeklySchedules");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Payment", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("WebhookEvents");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.PlatformUser", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("ProcessedWithdrawalRequests");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Product", b =>
                {
                    b.Navigation("StockHistories");

                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.SharedPosDevice", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Tenant", b =>
                {
                    b.Navigation("Absensis");

                    b.Navigation("AttendanceCorrections");

                    b.Navigation("AttendancePolicies");

                    b.Navigation("Customers");

                    b.Navigation("EmployeeScheduleExceptions");

                    b.Navigation("EmployeeWeeklySchedules");

                    b.Navigation("Karyawans");

                    b.Navigation("PaymentLedgerEntries");

                    b.Navigation("PaymentRoutes");

                    b.Navigation("PaymentWebhookEvents");

                    b.Navigation("Payments");

                    b.Navigation("PlatformAuditEvents");

                    b.Navigation("Products");

                    b.Navigation("Settings");

                    b.Navigation("SharedPosDevices");

                    b.Navigation("SharedPosSessions");

                    b.Navigation("StockHistories");

                    b.Navigation("TenantAuditEvents");

                    b.Navigation("TransactionItems");

                    b.Navigation("Transactions");

                    b.Navigation("Users");

                    b.Navigation("WithdrawalRequests");

                    b.Navigation("WithdrawalRoutes");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.Transaction", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.User", b =>
                {
                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("NeverfadePos.Api.Entities.WithdrawalRequest", b =>
                {
                    b.Navigation("LedgerEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
